[tool.poetry]
name = "aoc2022"
version = "0.1.0"
description = ""
authors = ["Mark Sharpley <mark.sharpley@statsbomb.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
